### ISSUE TITLE
hello dear 

### ISSUE THREAD

**Issue by Mabdelwanis** [hackcatml/mldecrypt#1]
unfortunately, not work on ios 15 rootless jailbreak.

**Comment by hackcatml** [comment]
hello. I updated it :)

**Comment by Mabdelwanis** [comment]
thanks i tried it many times but got this error every time 
Okay. It's ready to decrypt "bundle id"'s binary 
Launching the app... 
Something went wrong. retry

**Comment by hackcatml** [comment]
It seems that the tweak didn't get injected into the target process properly
If it works fine, you should see these logs on Console.app

```
[hackcatml] mldecryptor start
[hackcatml] binary dump started
[hackcatml] binary dump done at /var/mobile/Documents/xxx.decrypted
```

Other tweaks are working well on your device?
I should mention that the rootless version was only tested on iPhone X iOS 15.6.1 palera1n jb. Therefore, It might not work on dopamine jb...

**Comment by Mabdelwanis** [comment]
it's may be dopamine related issue nvm thanks a a lot for your tries 
and i would thank you again about your amazing blog but in ios section some articles need password to read can i read this articles

**Comment by 4dollar4** [comment]
Unfortunatly, It isn't working..
It is stuck when I was trying to attemp for decrypt.

```
xxxxx-ui-iPad:/tmp mobile% mldecrypt -b com.xxxx.xxxx

Okay. It's ready to decrypt "com.frograms.WATCHAPLAY"'s binary
Launching the app...

Something went wrong while decrypting binary. retry
```

My device: iPad 5th(2017), 15.2(iOS), rootless jailbreak

**Comment by hyunjong-prestolabs** [comment]
This is my dependancies problem. It seems to similar the bfdecrypt.
I have installed several modules, including ldid, altlist and they work fine. It would be nice to specify the required dependency modules in the readme.

**Comment by 4dollar4** [comment]
This is my dependancies problem. It seems to similar the bfdecrypt.
I have installed several modules, including ldid, altlist and they work fine. It would be nice to specify the required dependency modules in the readme.

**Comment by hackcatml** [comment]
> This is my dependancies problem. It seems to similar the bfdecrypt. I have installed several modules, including ldid, altlist and they work fine. It would be nice to specify the required dependency modules in the readme.

I updated the readme, thanks
